### ISSUE TITLE
When searching with ⌥ + G, it doesn't work correctly

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#6] opened 2016-12-31 14:26 UTC
I get this : 

![2016-12-31 at 15 25](https://cloud.githubusercontent.com/assets/6391776/21577935/81fc28c0-cf6d-11e6-9b08-65d20b3ad317.png)

Some white transparent text on the top and the results are strange too. Is this intended?

**Comment by ashfinal** [comment] 2017-01-01 06:36
Ew … Yes, it works as intended, but not all.

![hsearch-1](https://github.com/ashfinal/bindata/raw/master/screenshots/orphan-hsearch.png)

The below uses `youdao dict`’s data (an English-Chinese translation service based in China). If you type really fast, the chance is the returned results may not catch up with you due to the network latency. But still, you can use English thesaurus (Ctrl + D).

The white transparent text on the top is “autosuggestions” (something like that), which is not part of Hammerspoon Chooser control. I simply “draw" a text frame above Chooser control to place word suggestions. The drawback is the text frame’s appearance don’t match Chooser control very well, though I could use more time to adjust it, even make its appearance to change according to the system’s Dark Mode preference.

For now if you found it is useless and disturbing, feel free to use the line below to disable it.

`usesuggest = false`

I'm thinking maybe I can put word suggestions into the below, and when the users stop typing for certain interval, retrieve translation data and replace the original data below. But I still need time to verify and test.

**Comment by nikivdev** [comment] 2017-01-01 12:50
This makes sense, thank you.

I guess, this isn't really useful for me, only the thesaurus part is. :)

I wanted to ask you. How can I turn off all modes aside from RESIZE and VIEW : 

![2017-01-01 at 13 48](https://cloud.githubusercontent.com/assets/6391776/21581231/30f79178-d029-11e6-8bf3-ec8d992bf2ff.png)

I don't want them taking hotkeys as I want to use them for other things.

**Comment by ashfinal** [comment] 2017-01-01 13:31
Yes, you can remove the default modules and add your own. See `README.md` 's Customization section.
Add the snippet below into `~/.hammerspoon/awesomeconfig.lua`
```
module_list = {
    "basicmode",
}
```
You may find some hotkeys still work. From I can see from the above screenshot, including:
1.  Enter app mode - OPT + A
2. Open Hammerspoon console - OPT + Z
3. Show window hints - OPT + Tab
Those hotkeys exists because their code are too short, creating a new module/file is not economic, so they are merged into one module/file.

Still, yes, you can modify these hotkeys or simply disable them.
```
appM_keys = {{}, ""}
toggleconsole_keys = {{}, ""}
winhints_keys = {{}, ""}
```

**Comment by nikivdev** [comment] 2017-01-01 13:42
Thank you, this is perfect.

**Closed as completed** 2017-01-01 13:48 UTC
